version: "2"
linters:
  default: standard
  enable:
    - unparam
  settings:
    staticcheck:
      dot-import-whitelist:
        - fmt
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'

issues:
  max-same-issues: 100

  exclude-files:
    - generated.*\\.go

  exclude-dirs:
    - client
    - vendor

run:
  timeout: 10m
