/*
Copyright The Searchlight Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DashboardListerExpansion allows custom methods to be added to
// DashboardLister.
type DashboardListerExpansion interface{}

// DashboardNamespaceListerExpansion allows custom methods to be added to
// DashboardNamespaceLister.
type DashboardNamespaceListerExpansion interface{}

// DashboardTemplateListerExpansion allows custom methods to be added to
// DashboardTemplateLister.
type DashboardTemplateListerExpansion interface{}

// DashboardTemplateNamespaceListerExpansion allows custom methods to be added to
// DashboardTemplateNamespaceLister.
type DashboardTemplateNamespaceListerExpansion interface{}

// DatasourceListerExpansion allows custom methods to be added to
// DatasourceLister.
type DatasourceListerExpansion interface{}

// DatasourceNamespaceListerExpansion allows custom methods to be added to
// DatasourceNamespaceLister.
type DatasourceNamespaceListerExpansion interface{}
