/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: go.openviz.dev/grafana-tools/apis/ui/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *DashboardRef) Reset()      { *m = DashboardRef{} }
func (*DashboardRef) ProtoMessage() {}
func (*DashboardRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{0}
}
func (m *DashboardRef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DashboardRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DashboardRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardRef.Merge(m, src)
}
func (m *DashboardRef) XXX_Size() int {
	return m.Size()
}
func (m *DashboardRef) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardRef.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardRef proto.InternalMessageInfo

func (m *DashboardSelector) Reset()      { *m = DashboardSelector{} }
func (*DashboardSelector) ProtoMessage() {}
func (*DashboardSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{1}
}
func (m *DashboardSelector) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DashboardSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DashboardSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardSelector.Merge(m, src)
}
func (m *DashboardSelector) XXX_Size() int {
	return m.Size()
}
func (m *DashboardSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardSelector.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardSelector proto.InternalMessageInfo

func (m *EmbeddedDashboard) Reset()      { *m = EmbeddedDashboard{} }
func (*EmbeddedDashboard) ProtoMessage() {}
func (*EmbeddedDashboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{2}
}
func (m *EmbeddedDashboard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmbeddedDashboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EmbeddedDashboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedDashboard.Merge(m, src)
}
func (m *EmbeddedDashboard) XXX_Size() int {
	return m.Size()
}
func (m *EmbeddedDashboard) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedDashboard.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedDashboard proto.InternalMessageInfo

func (m *EmbeddedDashboardRequest) Reset()      { *m = EmbeddedDashboardRequest{} }
func (*EmbeddedDashboardRequest) ProtoMessage() {}
func (*EmbeddedDashboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{3}
}
func (m *EmbeddedDashboardRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmbeddedDashboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EmbeddedDashboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedDashboardRequest.Merge(m, src)
}
func (m *EmbeddedDashboardRequest) XXX_Size() int {
	return m.Size()
}
func (m *EmbeddedDashboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedDashboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedDashboardRequest proto.InternalMessageInfo

func (m *EmbeddedDashboardResponse) Reset()      { *m = EmbeddedDashboardResponse{} }
func (*EmbeddedDashboardResponse) ProtoMessage() {}
func (*EmbeddedDashboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{4}
}
func (m *EmbeddedDashboardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmbeddedDashboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EmbeddedDashboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedDashboardResponse.Merge(m, src)
}
func (m *EmbeddedDashboardResponse) XXX_Size() int {
	return m.Size()
}
func (m *EmbeddedDashboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedDashboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedDashboardResponse proto.InternalMessageInfo

func (m *EmbeddedDashboardStatus) Reset()      { *m = EmbeddedDashboardStatus{} }
func (*EmbeddedDashboardStatus) ProtoMessage() {}
func (*EmbeddedDashboardStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{5}
}
func (m *EmbeddedDashboardStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmbeddedDashboardStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EmbeddedDashboardStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedDashboardStatus.Merge(m, src)
}
func (m *EmbeddedDashboardStatus) XXX_Size() int {
	return m.Size()
}
func (m *EmbeddedDashboardStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedDashboardStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedDashboardStatus proto.InternalMessageInfo

func (m *PanelURL) Reset()      { *m = PanelURL{} }
func (*PanelURL) ProtoMessage() {}
func (*PanelURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4e2fa1ec64fe07, []int{6}
}
func (m *PanelURL) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PanelURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PanelURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PanelURL.Merge(m, src)
}
func (m *PanelURL) XXX_Size() int {
	return m.Size()
}
func (m *PanelURL) XXX_DiscardUnknown() {
	xxx_messageInfo_PanelURL.DiscardUnknown(m)
}

var xxx_messageInfo_PanelURL proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DashboardRef)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.DashboardRef")
	proto.RegisterType((*DashboardSelector)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.DashboardSelector")
	proto.RegisterType((*EmbeddedDashboard)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.EmbeddedDashboard")
	proto.RegisterType((*EmbeddedDashboardRequest)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.EmbeddedDashboardRequest")
	proto.RegisterType((*EmbeddedDashboardResponse)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.EmbeddedDashboardResponse")
	proto.RegisterType((*EmbeddedDashboardStatus)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.EmbeddedDashboardStatus")
	proto.RegisterType((*PanelURL)(nil), "go.openviz.dev.grafana_tools.apis.ui.v1alpha1.PanelURL")
}

func init() {
	proto.RegisterFile("go.openviz.dev/grafana-tools/apis/ui/v1alpha1/generated.proto", fileDescriptor_5e4e2fa1ec64fe07)
}

var fileDescriptor_5e4e2fa1ec64fe07 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xce, 0x36, 0xa9, 0x9a, 0xae, 0xfb, 0xf6, 0x55, 0x8d, 0x04, 0x69, 0x85, 0x9c, 0xc8, 0x5c,
	0x72, 0xe9, 0x5a, 0xad, 0xf8, 0x92, 0x10, 0x08, 0x59, 0xad, 0xca, 0xa1, 0xaa, 0xd0, 0x96, 0x1e,
	0xe8, 0x05, 0x6d, 0xe2, 0xb1, 0x63, 0x1a, 0x7b, 0xcd, 0xee, 0x3a, 0x12, 0x9c, 0x38, 0x73, 0xe2,
	0xc8, 0x5f, 0xe0, 0x9f, 0xf4, 0xd8, 0x63, 0x4f, 0x11, 0x35, 0x3f, 0x82, 0x2b, 0xca, 0x7a, 0x9d,
	0xb4, 0x8d, 0x2a, 0x54, 0xb8, 0x79, 0x3c, 0xf3, 0x7c, 0xec, 0xcc, 0x83, 0x9f, 0x47, 0x9c, 0xf0,
	0x0c, 0xd2, 0x51, 0xfc, 0x89, 0x04, 0x30, 0xf2, 0x22, 0xc1, 0x42, 0x96, 0xb2, 0x4d, 0xc5, 0xf9,
	0x50, 0x7a, 0x2c, 0x8b, 0xa5, 0x97, 0xc7, 0xde, 0x68, 0x8b, 0x0d, 0xb3, 0x01, 0xdb, 0xf2, 0x22,
	0x48, 0x41, 0x30, 0x05, 0x01, 0xc9, 0x04, 0x57, 0xdc, 0xde, 0xbc, 0x0a, 0x27, 0x06, 0xfe, 0x4e,
	0xc3, 0xc9, 0x04, 0x4e, 0xf2, 0x98, 0x54, 0xf0, 0x8d, 0xcd, 0x28, 0x56, 0x83, 0xbc, 0x47, 0xfa,
	0x3c, 0xf1, 0x22, 0x1e, 0x71, 0x4f, 0xb3, 0xf4, 0xf2, 0x50, 0x57, 0xba, 0xd0, 0x5f, 0x25, 0xfb,
	0xc6, 0xc3, 0x93, 0xa7, 0x92, 0xc4, 0x7c, 0x62, 0x23, 0x61, 0xfd, 0x41, 0x9c, 0x82, 0xf8, 0xe8,
	0x65, 0x27, 0x51, 0xe9, 0x2b, 0x01, 0xc5, 0xbc, 0xd1, 0x9c, 0xa7, 0x0d, 0xef, 0x26, 0x94, 0xc8,
	0x53, 0x15, 0x27, 0x30, 0x07, 0x78, 0xfc, 0x27, 0x80, 0xec, 0x0f, 0x20, 0x61, 0xd7, 0x71, 0xee,
	0x37, 0x84, 0x57, 0x76, 0x98, 0x1c, 0xf4, 0x38, 0x13, 0x01, 0x85, 0xd0, 0xbe, 0x8f, 0x1b, 0x29,
	0x4b, 0xa0, 0x85, 0x3a, 0xa8, 0xbb, 0xec, 0x37, 0x8b, 0x71, 0xbb, 0x71, 0xc0, 0x12, 0xa0, 0xfa,
	0xaf, 0xfd, 0x1e, 0x37, 0x25, 0x0c, 0xa1, 0xaf, 0xb8, 0x68, 0x2d, 0x74, 0x50, 0xd7, 0xda, 0x7e,
	0x49, 0x6e, 0xb5, 0x3e, 0x32, 0x15, 0x3b, 0x34, 0x3c, 0xfe, 0x4a, 0x31, 0x6e, 0x37, 0xab, 0x8a,
	0x4e, 0xf9, 0xdd, 0x2f, 0x08, 0xaf, 0xcd, 0x4d, 0xdb, 0x8f, 0xb0, 0x65, 0x14, 0x0e, 0x66, 0x36,
	0xef, 0x9c, 0x8e, 0xdb, 0xb5, 0x62, 0xdc, 0xb6, 0xf6, 0x66, 0x2d, 0x7a, 0x79, 0xce, 0x7e, 0x81,
	0x57, 0x83, 0x8a, 0xeb, 0x4d, 0xac, 0x86, 0xa0, 0xed, 0x2f, 0xfb, 0x77, 0x0d, 0x72, 0x75, 0xe7,
	0x4a, 0x97, 0x5e, 0x9b, 0x76, 0x7f, 0x21, 0xbc, 0xb6, 0x9b, 0xf4, 0x20, 0x08, 0x20, 0x98, 0x8e,
	0xda, 0x29, 0x5e, 0x12, 0xf0, 0x21, 0x07, 0xa9, 0xb4, 0x11, 0x6b, 0x7b, 0xef, 0x96, 0xdb, 0x98,
	0xa3, 0xa4, 0x25, 0x9d, 0x6f, 0x15, 0xe3, 0xf6, 0x92, 0x29, 0x68, 0x25, 0x62, 0x0b, 0xdc, 0x14,
	0x20, 0x33, 0x9e, 0x4a, 0x30, 0xeb, 0x7f, 0xf5, 0xef, 0x82, 0x25, 0x5f, 0x79, 0x86, 0xaa, 0xa2,
	0x53, 0x1d, 0xf7, 0x3b, 0xc2, 0xad, 0x9b, 0x6c, 0xda, 0xc7, 0xb8, 0x2e, 0x20, 0x34, 0x8f, 0x7f,
	0xf6, 0xb7, 0x51, 0xa0, 0x10, 0xfa, 0x96, 0x39, 0x44, 0x9d, 0x42, 0x48, 0x27, 0xa4, 0xf6, 0x16,
	0xb6, 0x32, 0x96, 0xc2, 0x50, 0x1f, 0x40, 0xb6, 0x16, 0x3a, 0xf5, 0xee, 0xb2, 0xff, 0xff, 0xe4,
	0xca, 0xaf, 0x67, 0xbf, 0xe9, 0xe5, 0x19, 0x77, 0x84, 0xd7, 0x6f, 0x7c, 0xa0, 0xfd, 0x16, 0x37,
	0x72, 0x31, 0x94, 0x2d, 0xd4, 0xa9, 0x77, 0xad, 0xed, 0x27, 0xb7, 0x34, 0xab, 0x35, 0x8f, 0xe8,
	0xbe, 0xbf, 0x62, 0x8c, 0x36, 0x8e, 0xe8, 0xbe, 0xa4, 0x9a, 0xd2, 0x5d, 0xc7, 0xf7, 0xe6, 0x74,
	0x0f, 0x15, 0x53, 0xb9, 0x74, 0x43, 0xdc, 0xac, 0xa0, 0xf6, 0x03, 0xbc, 0xa8, 0x74, 0xf6, 0xca,
	0xd4, 0xfe, 0x67, 0x98, 0x16, 0xcb, 0xc8, 0x95, 0xbd, 0x49, 0xc0, 0xc1, 0x70, 0x1d, 0xd1, 0x7d,
	0x13, 0xd3, 0x69, 0xc0, 0x77, 0x67, 0x2d, 0x7a, 0x79, 0xce, 0x27, 0xa7, 0x17, 0x4e, 0xed, 0xec,
	0xc2, 0xa9, 0x9d, 0x5f, 0x38, 0xb5, 0xcf, 0x85, 0x83, 0x4e, 0x0b, 0x07, 0x9d, 0x15, 0x0e, 0x3a,
	0x2f, 0x1c, 0xf4, 0xa3, 0x70, 0xd0, 0xd7, 0x9f, 0x4e, 0xed, 0xb8, 0x59, 0xbd, 0xe7, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x93, 0x68, 0x37, 0x03, 0x35, 0x05, 0x00, 0x00,
}

func (m *DashboardRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DashboardRef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DashboardRef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Selector != nil {
		{
			size, err := m.Selector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Name != nil {
		i -= len(*m.Name)
		copy(dAtA[i:], *m.Name)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DashboardSelector) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DashboardSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DashboardSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.DashboardTitle)
	copy(dAtA[i:], m.DashboardTitle)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DashboardTitle)))
	i--
	dAtA[i] = 0x12
	i -= len(m.GrafanaName)
	copy(dAtA[i:], m.GrafanaName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.GrafanaName)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EmbeddedDashboard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmbeddedDashboard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmbeddedDashboard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Response != nil {
		{
			size, err := m.Response.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Request != nil {
		{
			size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EmbeddedDashboardRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmbeddedDashboardRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmbeddedDashboardRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PanelTitles) > 0 {
		for iNdEx := len(m.PanelTitles) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PanelTitles[iNdEx])
			copy(dAtA[i:], m.PanelTitles[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.PanelTitles[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Ref.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EmbeddedDashboardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmbeddedDashboardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmbeddedDashboardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.URLs) > 0 {
		for iNdEx := len(m.URLs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.URLs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EmbeddedDashboardStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmbeddedDashboardStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmbeddedDashboardStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PanelURL) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PanelURL) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PanelURL) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.EmbeddedURL)
	copy(dAtA[i:], m.EmbeddedURL)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.EmbeddedURL)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Title)
	copy(dAtA[i:], m.Title)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Title)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DashboardRef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Name != nil {
		l = len(*m.Name)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Selector != nil {
		l = m.Selector.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *DashboardSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GrafanaName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.DashboardTitle)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *EmbeddedDashboard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Request != nil {
		l = m.Request.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Response != nil {
		l = m.Response.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *EmbeddedDashboardRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Ref.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.PanelTitles) > 0 {
		for _, s := range m.PanelTitles {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *EmbeddedDashboardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.URLs) > 0 {
		for _, e := range m.URLs {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *EmbeddedDashboardStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PanelURL) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.EmbeddedURL)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DashboardRef) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DashboardRef{`,
		`Name:` + valueToStringGenerated(this.Name) + `,`,
		`Selector:` + strings.Replace(this.Selector.String(), "DashboardSelector", "DashboardSelector", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DashboardSelector) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DashboardSelector{`,
		`GrafanaName:` + fmt.Sprintf("%v", this.GrafanaName) + `,`,
		`DashboardTitle:` + fmt.Sprintf("%v", this.DashboardTitle) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EmbeddedDashboard) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EmbeddedDashboard{`,
		`Request:` + strings.Replace(this.Request.String(), "EmbeddedDashboardRequest", "EmbeddedDashboardRequest", 1) + `,`,
		`Response:` + strings.Replace(this.Response.String(), "EmbeddedDashboardResponse", "EmbeddedDashboardResponse", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EmbeddedDashboardRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EmbeddedDashboardRequest{`,
		`Ref:` + strings.Replace(strings.Replace(this.Ref.String(), "DashboardRef", "DashboardRef", 1), `&`, ``, 1) + `,`,
		`PanelTitles:` + fmt.Sprintf("%v", this.PanelTitles) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EmbeddedDashboardResponse) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForURLs := "[]PanelURL{"
	for _, f := range this.URLs {
		repeatedStringForURLs += strings.Replace(strings.Replace(f.String(), "PanelURL", "PanelURL", 1), `&`, ``, 1) + ","
	}
	repeatedStringForURLs += "}"
	s := strings.Join([]string{`&EmbeddedDashboardResponse{`,
		`URLs:` + repeatedStringForURLs + `,`,
		`}`,
	}, "")
	return s
}
func (this *EmbeddedDashboardStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EmbeddedDashboardStatus{`,
		`}`,
	}, "")
	return s
}
func (this *PanelURL) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PanelURL{`,
		`Title:` + fmt.Sprintf("%v", this.Title) + `,`,
		`EmbeddedURL:` + fmt.Sprintf("%v", this.EmbeddedURL) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DashboardRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DashboardRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DashboardRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Name = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Selector == nil {
				m.Selector = &DashboardSelector{}
			}
			if err := m.Selector.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DashboardSelector) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DashboardSelector: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DashboardSelector: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrafanaName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrafanaName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DashboardTitle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DashboardTitle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmbeddedDashboard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmbeddedDashboard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmbeddedDashboard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Request == nil {
				m.Request = &EmbeddedDashboardRequest{}
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Response == nil {
				m.Response = &EmbeddedDashboardResponse{}
			}
			if err := m.Response.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmbeddedDashboardRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmbeddedDashboardRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmbeddedDashboardRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ref", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ref.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PanelTitles", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PanelTitles = append(m.PanelTitles, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmbeddedDashboardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmbeddedDashboardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmbeddedDashboardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URLs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URLs = append(m.URLs, PanelURL{})
			if err := m.URLs[len(m.URLs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmbeddedDashboardStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmbeddedDashboardStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmbeddedDashboardStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PanelURL) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PanelURL: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PanelURL: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmbeddedURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmbeddedURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
