//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	v1 "kmodules.xyz/client-go/api/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardGroupLink) DeepCopyInto(out *DashboardGroupLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(DashboardGroupLinkRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(DashboardGroupLinkResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardGroupLink.
func (in *DashboardGroupLink) DeepCopy() *DashboardGroupLink {
	if in == nil {
		return nil
	}
	out := new(DashboardGroupLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardGroupLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardGroupLinkRequest) DeepCopyInto(out *DashboardGroupLinkRequest) {
	*out = *in
	if in.Dashboards != nil {
		in, out := &in.Dashboards, &out.Dashboards
		*out = make([]DashboardLinkRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TimeRange != nil {
		in, out := &in.TimeRange, &out.TimeRange
		*out = new(TimeRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardGroupLinkRequest.
func (in *DashboardGroupLinkRequest) DeepCopy() *DashboardGroupLinkRequest {
	if in == nil {
		return nil
	}
	out := new(DashboardGroupLinkRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardGroupLinkResponse) DeepCopyInto(out *DashboardGroupLinkResponse) {
	*out = *in
	if in.Dashboards != nil {
		in, out := &in.Dashboards, &out.Dashboards
		*out = make([]DashboardLinkResponse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardGroupLinkResponse.
func (in *DashboardGroupLinkResponse) DeepCopy() *DashboardGroupLinkResponse {
	if in == nil {
		return nil
	}
	out := new(DashboardGroupLinkResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLinkRequest) DeepCopyInto(out *DashboardLinkRequest) {
	*out = *in
	in.DashboardRef.DeepCopyInto(&out.DashboardRef)
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]DashboardVar, len(*in))
		copy(*out, *in)
	}
	if in.Panels != nil {
		in, out := &in.Panels, &out.Panels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLinkRequest.
func (in *DashboardLinkRequest) DeepCopy() *DashboardLinkRequest {
	if in == nil {
		return nil
	}
	out := new(DashboardLinkRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLinkResponse) DeepCopyInto(out *DashboardLinkResponse) {
	*out = *in
	in.DashboardRef.DeepCopyInto(&out.DashboardRef)
	if in.Panels != nil {
		in, out := &in.Panels, &out.Panels
		*out = make([]PanelLink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLinkResponse.
func (in *DashboardLinkResponse) DeepCopy() *DashboardLinkResponse {
	if in == nil {
		return nil
	}
	out := new(DashboardLinkResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardRef) DeepCopyInto(out *DashboardRef) {
	*out = *in
	if in.ObjectReference != nil {
		in, out := &in.ObjectReference, &out.ObjectReference
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardRef.
func (in *DashboardRef) DeepCopy() *DashboardRef {
	if in == nil {
		return nil
	}
	out := new(DashboardRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardVar) DeepCopyInto(out *DashboardVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardVar.
func (in *DashboardVar) DeepCopy() *DashboardVar {
	if in == nil {
		return nil
	}
	out := new(DashboardVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelLink) DeepCopyInto(out *PanelLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelLink.
func (in *PanelLink) DeepCopy() *PanelLink {
	if in == nil {
		return nil
	}
	out := new(PanelLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeRange) DeepCopyInto(out *TimeRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeRange.
func (in *TimeRange) DeepCopy() *TimeRange {
	if in == nil {
		return nil
	}
	out := new(TimeRange)
	in.DeepCopyInto(out)
	return out
}
